### ISSUE TITLE
Support multiple instances of this attribute

### ISSUE THREAD

**Issue by royweston** [Mesuva/multi_page_selector_attribute_legacy#1]
Allow multiple instances of this attribute to appear on a page type. Currently updating one also updates the other in the ui.

**Comment by Mesuva** [comment]
I've rewritten a lot of the javascript to make this now possible. There's actually a limitation to concrete5's page selector javascript, which made it much more difficult to achieve (so the code is a little bit of a creative workaround). Testing would be appreciated.
